# Array Programming in Numpy

## 1 Indexing and Slicing

Often, we want to access specific values stored inside an array. This
can be done by slicing and indexing. Indexing simply means getting the
element at a specific position. Python starts counting at 0, so `x[0]`
will get the **1st** element of `x`. Slicing means getting all values
within a certain range by providing a start and stop position. When we
index and slice multi-dimensional arrays, we must provide multiple
coordinates - one per dimension. We can also omit a value to indicate
that we want to get **all** values along that dimension

Execute the cell below to install the packages required for this
notebook.

In [ ]:
%pip install numpy

| Code | Description |
|------------------------------------|------------------------------------|
| `import numpy as np` | Import the module `numpy` under the alias `np` |
| `x = np.arange(2,7)` | Create an array with all integers between 2 and (not including) 7 and assign it to the variable `x` |
| `x[0]` | Get the 1st element of `x` |
| `x[-1]` | Get the last element of `x` |
| `x[2:5]` | Get the 3rd 4th and 5th elements of `x` |
| `x[:5]` | Get everything up to and including the 5th element of `x` |
| `x[2, 1]` | Get the element in the 3rd row and 2nd column of the 2-dimensional array `x` |
| `x[0, :]` | Get the whole first row of `x` |
| `x[1:5, 2]` | Get the values from rows 2 through 5 in the 3rd column of `x` |

------------------------------------------------------------------------

<span class="theorem-title">**Exercise 1**</span> Import the Numpy
module under the alias `np`.

In [46]:
import numpy as np

<span class="theorem-title">**Exercise 2**</span> Create an array with
the integers between 1 and 10 and assign it to a variable `x`.

In [48]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<span class="theorem-title">**Exercise 3**</span> Get the second element
of `x`.

In [49]:
x[1]

np.int64(2)

<span class="theorem-title">**Exercise 4**</span> Get the second-to-last
element of `x`.

In [50]:
x[-2]

np.int64(8)

<span class="theorem-title">**Exercise 5**</span> Get all the elements
of `x` except for the first two.

In [53]:
x[2:]

array([3, 4, 5, 6, 7, 8, 9])

<span class="theorem-title">**Exercise 6**</span> Get all elements of
`x` except for the first and last.

In [54]:
x[1:-1]

array([2, 3, 4, 5, 6, 7, 8])

<span class="theorem-title">**Exercise 7**</span> Run the cell below
to define the 2-dimensional array `x`. (You don't need to add or change any code.)

In [55]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

<span class="theorem-title">**Example 1**</span> Get the first row of
`x` with the values `[1, 2, 3]`.

In [56]:
x[0, :]

array([1, 2, 3])

<span class="theorem-title">**Exercise 8**</span> Get the second column
of `x` with the values `[2, 5, 8]`.

In [10]:
x[1]

array([4, 5, 6])

<span class="theorem-title">**Exercise 9**</span> Get every value of
`x` except for the bottom row.

In [11]:
x[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
x[:, 1]

array([2, 5, 8])

<span class="theorem-title">**Exercise 10**</span> Get every value of
`x` except for the rightmost column.

In [60]:
x[:,:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

## 2 Filtering

Another way to get specific values from arrays is by filtering. By
filtering, we can extract values from an array based on a specific
condition. For example, we can get all values that are greater than 0.
Filtering can be divided into two steps: 1. Create a mask that specifies
which elements meet the condition. 2. Apply the mask to the array to
filter it. By creating different masks we can vary the criteria for
selecting data from an array.

| Code | Description |
|------------------------------------|------------------------------------|
| `mask = x>1` | Create a `mask` that is `True` where `x` is greater than `1` and `False` otherwise |
| `mask = x=="k"` | Create a `mask` that is `True` where `x` is equal to `"k"` and `False` otherwise |
| `mask = x<=1` | Create a `mask` that is `True` where `x` is smaller than or equal to `1` and `False` otherwise |
| `x[mask]` | Get all elements of `x` where the `mask` is `True` |
| `np.sum(mask)` | Sum all elements of the `mask` (`True` counts as 1, `False` as 0) |
| `np.size(mask)` | Get the number of elements in `x` |
| `x = np.random.randint(low=5, high=15, size=20)` | Create an array with `20` random integers between `5` and `15` and assign it to the variable `x` |

------------------------------------------------------------------------

<span class="theorem-title">**Exercise 11**</span> Create an array with
100 random integers between 0 and 10 and assign it to the variable `x`.

In [65]:
x = np.random.randint(low=0,high=10,size=20)
x

array([2, 1, 9, 4, 2, 6, 3, 1, 1, 1, 4, 2, 0, 6, 0, 2, 5, 1, 8, 7],
      dtype=int32)

<span class="theorem-title">**Example 2**</span> Get all values of x
that are smaller than 5.

In [67]:
mask = x<5
mask

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False, False])

In [68]:
x[mask]

array([2, 1, 4, 2, 3, 1, 1, 1, 4, 2, 0, 0, 2, 1], dtype=int32)

<span class="theorem-title">**Exercise 12**</span> Get all values of `x`
that are greater than 3.

In [69]:
mask = x>3
x[mask]

array([9, 4, 6, 4, 6, 5, 8, 7], dtype=int32)

<span class="theorem-title">**Exercise 13**</span> Get all values of `x`
that are smaller than or equal to 2.

In [70]:
mask = x<=2
x[mask]

array([2, 1, 2, 1, 1, 1, 2, 0, 0, 2, 1], dtype=int32)

<span class="theorem-title">**Exercise 14**</span> Execute the cell
below to define an array containing a gene sequence. Then, get all
adenine (`"A"`) nucleotides from this array.

In [71]:
seq = np.array(["A", "T", "G", "C", "G", "T", "A", "C", "G", "T", "T", "A", "G", "C", "T", "A", "G", "G", "C", "T", "T", "A", "C", "G", "A", "T", "C", "G", "T", "A"])

In [74]:
mask = seq == "A"
mask

array([ True, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False,  True])

In [75]:
seq[mask]

array(['A', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U1')

<span class="theorem-title">**Exercise 15**</span> Is there more
cytosine (`"C"`) or guanine (`"G"`) in the sequence?

In [19]:
np.size(seq[seq=='G']), np.size(seq[seq=='C'])

(8, 6)

## 3 Analyzing Multi-Dimensional Data

Now that we learned about indexing, slicing and filtering, we have the
tools for analyzing multidimensional data! In this section we are going
to analyze electroencephalography (EEG) recordings of brain responses to
pure tones. The data are stored in a 3-dimensional array, where the
dimensions represent: 1. The number of trials or epochs
(i.e. repetitions of the same stimulus) 2. The number of EEG channels 3.
The number of time points in the recording When we use Numpy functions
to compute properties like mean or standard deviation on a
multidimensional array, we can use the `axis` argument to select a
specific dimension.

| Code | Description |
|------------------------------------|------------------------------------|
| `x=np.load("myfile.npy")` | Load the data stored in `"myfile.npy"` and assign them to the variable `x` |
| `np.save("newfile.npy", x)` | Save the array `x` to a file called `"newfile.npy"` |
| `np.shape(x)` | Get the shape of `x` (i.e. the size of all dimensions of `x`) |
| `x[0, :, :]` | Select the 1st element along the 2nd dimension of the 3D array `x` |
| `x[:, 4:10, :]` | Select the elements 5 to 10 along the 2nd dimension of the 3D array `x` |
| `x[1, :, :3]` | Select the 1st element along the 1st dimension and the first 3 elements along the 3rd dimension of the 3D array `x` |
| `np.mean(x, axis=0)` | Compute the mean across the 1st dimension of `x` |
| `np.std(x, axis=2)` | Compute the standard deviation across the 3rd dimension of `x` |
| `np.max(x)` | Get the maximum value of `x` |

------------------------------------------------------------------------

<span class="theorem-title">**Exercise 16**</span> Run the cell below to load the data stored
in the file `eeg_epochs.npy` and assign it to a variable called `eeg`.

In [76]:
eeg = np.load('eeg_epochs.npy')

<span class="theorem-title">**Exercise 17**</span> How many epochs,
channels and time points are there in the `eeg` data? *Hint*: The `shape` function gives you the dimensions of a data array.

In [77]:
eeg.shape

(70, 59, 54)

<span class="theorem-title">**Exercise 18**</span> Select the data from
the first EEG channel.

In [80]:
import matplotlib.pyplot as plt

In [82]:
eeg[10,0,:]

array([ 8.46685778e-07,  3.24680755e-06,  1.44104669e-06, -5.23874667e-06,
       -9.40781096e-06, -7.06964036e-06, -2.01591508e-06, -2.76071098e-08,
       -2.14111229e-06, -3.00936926e-06,  1.69728924e-06,  5.45963993e-06,
       -2.09637902e-06, -1.52847727e-05, -1.53210430e-05, -3.41384017e-07,
        7.74924862e-06, -2.20866040e-06, -1.20600107e-05, -5.74890901e-06,
        4.19045764e-06,  9.55466474e-07, -7.26826137e-06, -4.26165200e-06,
        5.35181675e-06,  6.03533740e-06, -1.97955574e-06, -5.08156084e-06,
        1.94836782e-06,  1.09823616e-05,  1.34224798e-05,  8.85044718e-06,
        2.73414857e-06, -1.19880342e-07, -3.25863911e-07, -1.88777079e-06,
       -5.19203854e-06, -6.06517520e-06, -3.09916984e-06, -4.13825115e-07,
       -1.16908768e-06, -3.48012448e-06, -3.98370333e-06, -1.05071093e-06,
        4.90379635e-06,  1.01772581e-05,  9.59358726e-06,  3.85388728e-06,
        4.20905863e-07,  2.48292061e-06,  3.79935676e-06,  2.86379780e-07,
       -1.80121388e-06,  

<span class="theorem-title">**Exercise 19**</span> Select the data from
the first 10 epochs for the 5th EEG channel.

In [23]:
eeg[:10, 4]

array([[ 1.39659765e-05,  1.94901918e-05,  2.80597018e-05,
         3.51590150e-05,  3.70034831e-05,  3.65254568e-05,
         3.85490080e-05,  4.18792123e-05,  4.12654958e-05,
         3.54950130e-05,  2.84851788e-05,  2.26845773e-05,
         1.61354493e-05,  7.54263591e-06,  5.81742826e-07,
        -6.74103167e-09,  4.95961635e-06,  9.76406387e-06,
         1.07279989e-05,  9.19449400e-06,  7.60127597e-06,
         6.43336564e-06,  5.70927773e-06,  5.62196261e-06,
         5.04526556e-06,  3.10944867e-06,  1.92681839e-06,
         3.45779694e-06,  5.17630336e-06,  4.30480985e-06,
         3.80653720e-06,  7.13100330e-06,  1.02197941e-05,
         7.65688613e-06,  3.70275756e-06,  6.70416145e-06,
         1.46686401e-05,  1.76239245e-05,  1.33006174e-05,
         9.30103348e-06,  9.74769420e-06,  1.05527914e-05,
         8.97118506e-06,  7.99553000e-06,  9.12369553e-06,
         8.97562557e-06,  5.85250288e-06,  3.37224821e-06,
         4.86250273e-06,  8.71811215e-06,  1.15144652e-0

In [84]:
np.shape(eeg)

(70, 59, 54)

In [86]:
avg_epochs = np.mean(eeg, axis = 0)
np.shape(avg_epochs)

(59, 54)

In [88]:
avg_eeg_channels = np.mean(eeg, axis = 1)
np.shape(avg_eeg_channels)

(70, 54)

<span class="theorem-title">**Exercise 20**</span> Compute the standard
deviation across all EEG channels - which is called the global field
potential (GFP) - and assign it to a new variable called `gfp`. What is
the shape of this array?

In [89]:
gfp = np.std(eeg, axis = 1)
gfp.shape

(70, 54)

<span class="theorem-title">**Exercise 21**</span> Save the GFP to a
file called `"gfp.npy"`. Then load the file again to make sure it was
stored.

In [90]:
np.save('gfp.npy', gfp)

In [92]:
gfp_check = np.load('gfp.npy')
np.shape(gfp_check)

(70, 54)

<span class="theorem-title">**Exercise 22**</span> Average the GFP
across all epochs and find the peak value of this average GFP.

In [27]:
np.mean(gfp, axis=0).max()

np.float64(7.1624821620567494e-06)

<span class="theorem-title">**Exercise 23**</span> Average the GFP
across time and epochs (so that the result is a single scalar value).
Compute this value separately for the first and second half of epochs -
which one is larger?

In [28]:
gfp[:,:int(gfp.shape[-1]/2)].mean(), gfp[:,int(gfp.shape[-1]/2):].mean()

(np.float64(6.150279958463817e-06), np.float64(6.662563282331686e-06))

## 4 Linking Arrays with Filtering

Filtering can also be used to link different arrays. In this section we
are going to load an array that contains the time points for the epochs
from the previous array. We can use that array to define a mask and then
apply that mask to the array of epoch. Numpy also allows us to combine
multiple masks using the and/or operators `&` and `|`. Combining two
Boolean arrays with `&` results in an array that is only `True` when
both arrays are `True`. Combining them with `|` results in an array that
is `True` when either array is `True`. In this section we are going to
use filtering to link the EEG data with the array containing the time
points at which the data were recorded (time point 0 represents the
stimulus onset).

<span class="theorem-title">**Exercise 24**</span> Load the data stored
in the file `epoch_times.npy` and assign it to a variable called
`times`.

In [93]:
times = np.load('epoch_times.npy')
times

array([0.        , 0.00665984, 0.01331968, 0.01997952, 0.02663936,
       0.0332992 , 0.03995904, 0.04661888, 0.05327872, 0.05993856,
       0.0665984 , 0.07325824, 0.07991809, 0.08657793, 0.09323777,
       0.09989761, 0.10655745, 0.11321729, 0.11987713, 0.12653697,
       0.13319681, 0.13985665, 0.14651649, 0.15317633, 0.15983617,
       0.16649601, 0.17315585, 0.17981569, 0.18647553, 0.19313537,
       0.19979521, 0.20645505, 0.21311489, 0.21977473, 0.22643457,
       0.23309442, 0.23975426, 0.2464141 , 0.25307394, 0.25973378,
       0.26639362, 0.27305346, 0.2797133 , 0.28637314, 0.29303298,
       0.29969282, 0.30635266, 0.3130125 , 0.31967234, 0.32633218,
       0.33299202, 0.33965186, 0.3463117 , 0.35297154])

In [94]:
eeg

array([[[ 2.67680334e-05,  3.53526848e-05,  4.69128998e-05, ...,
          4.12180852e-06, -3.86195567e-06, -2.89777466e-07],
        [ 2.76873252e-05,  3.94603314e-05,  5.36404585e-05, ...,
          8.87035035e-06,  3.93602730e-06,  4.56202645e-06],
        [ 2.70946471e-05,  4.35415728e-05,  5.87683795e-05, ...,
          3.53931110e-06, -5.56077119e-09, -4.33086722e-06],
        ...,
        [-5.04276237e-06, -7.37953656e-06, -9.72836155e-06, ...,
          4.44343545e-06,  4.31170682e-06,  2.03358772e-06],
        [-3.39345013e-06, -5.44104380e-06, -8.21716755e-06, ...,
          2.00014241e-06,  2.46326973e-06,  1.31696238e-06],
        [-7.43880044e-06, -1.07589566e-05, -1.50315333e-05, ...,
          1.05187075e-06,  4.35724880e-07, -1.82842560e-06]],

       [[-1.30239872e-05, -1.09115245e-05, -4.11188614e-06, ...,
         -7.63867312e-07,  6.58151272e-06,  6.19991800e-06],
        [-8.18649945e-06, -6.56655153e-06, -2.14800222e-06, ...,
          6.29634482e-06,  7.34611386e

<span class="theorem-title">**Exercise 25**</span> How many time points
are there? What’s the start and stop time?

In [30]:
np.size(times), times.min(), times.max()

(54, np.float64(0.0), np.float64(0.3529715432464852))

<span class="theorem-title">**Example 3**</span> Get all of the `eeg`
data that was recorded in the first 0.2 seconds after stimulus onset and
print the shape of the resulting array.

In [96]:
times

array([0.        , 0.00665984, 0.01331968, 0.01997952, 0.02663936,
       0.0332992 , 0.03995904, 0.04661888, 0.05327872, 0.05993856,
       0.0665984 , 0.07325824, 0.07991809, 0.08657793, 0.09323777,
       0.09989761, 0.10655745, 0.11321729, 0.11987713, 0.12653697,
       0.13319681, 0.13985665, 0.14651649, 0.15317633, 0.15983617,
       0.16649601, 0.17315585, 0.17981569, 0.18647553, 0.19313537,
       0.19979521, 0.20645505, 0.21311489, 0.21977473, 0.22643457,
       0.23309442, 0.23975426, 0.2464141 , 0.25307394, 0.25973378,
       0.26639362, 0.27305346, 0.2797133 , 0.28637314, 0.29303298,
       0.29969282, 0.30635266, 0.3130125 , 0.31967234, 0.32633218,
       0.33299202, 0.33965186, 0.3463117 , 0.35297154])

In [105]:
mask1 = times < 0.2
mask1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [106]:
eeg[:,:,mask1]

array([[[ 2.67680334e-05,  3.53526848e-05,  4.69128998e-05, ...,
          1.66172575e-06, -2.26350410e-07,  2.38564375e-06],
        [ 2.76873252e-05,  3.94603314e-05,  5.36404585e-05, ...,
          3.49214983e-06,  2.40684146e-06,  4.35802517e-06],
        [ 2.70946471e-05,  4.35415728e-05,  5.87683795e-05, ...,
          8.94707911e-08, -2.23653416e-06, -2.58973621e-06],
        ...,
        [-5.04276237e-06, -7.37953656e-06, -9.72836155e-06, ...,
          6.97940708e-06,  7.91734055e-06,  8.32545809e-06],
        [-3.39345013e-06, -5.44104380e-06, -8.21716755e-06, ...,
          8.94165363e-06,  8.62031167e-06,  7.82095945e-06],
        [-7.43880044e-06, -1.07589566e-05, -1.50315333e-05, ...,
          2.74133193e-06,  1.58138952e-07, -5.31656240e-07]],

       [[-1.30239872e-05, -1.09115245e-05, -4.11188614e-06, ...,
         -9.08296289e-06, -1.26353916e-05, -1.55128908e-05],
        [-8.18649945e-06, -6.56655153e-06, -2.14800222e-06, ...,
         -8.16375986e-06, -8.36451792e

<span class="theorem-title">**Exercise 26**</span> Get all of the `eeg`
data that was recorded in the first 0.05 seconds after stimulus onset
and print the shape of the resulting array.

In [32]:
mask = times < 0.05
np.shape(eeg[:,:,mask])

(70, 59, 8)

<span class="theorem-title">**Example 4**</span> Get all of the `eeg`
data that was recorded between 0.1 and 0.2 seconds after stimulus onset
and print the shape of the resulting array.

In [107]:
mask2 = (times>=0.1) & (times<=0.2)
mask2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [108]:
eeg[:,:,mask2]

array([[[ 2.80160261e-05,  2.59949301e-05,  2.68294130e-05, ...,
          1.66172575e-06, -2.26350410e-07,  2.38564375e-06],
        [ 2.76170501e-05,  3.18715226e-05,  3.08368527e-05, ...,
          3.49214983e-06,  2.40684146e-06,  4.35802517e-06],
        [ 2.79728694e-05,  3.10165105e-05,  3.10463504e-05, ...,
          8.94707911e-08, -2.23653416e-06, -2.58973621e-06],
        ...,
        [ 8.01735795e-06,  3.52157674e-06, -2.16066775e-08, ...,
          6.97940708e-06,  7.91734055e-06,  8.32545809e-06],
        [ 6.59051117e-06,  2.89922198e-06, -2.70402982e-07, ...,
          8.94165363e-06,  8.62031167e-06,  7.82095945e-06],
        [ 6.06759584e-06,  4.30270959e-06,  2.79291822e-06, ...,
          2.74133193e-06,  1.58138952e-07, -5.31656240e-07]],

       [[ 1.42250006e-06,  8.12658246e-06,  1.84651700e-06, ...,
         -9.08296289e-06, -1.26353916e-05, -1.55128908e-05],
        [ 1.76361866e-06,  6.62579841e-06,  4.08818220e-06, ...,
         -8.16375986e-06, -8.36451792e

<span class="theorem-title">**Exercise 27**</span> Get all of the `eeg`
data that was recorded before 0.1 and after 0.2 seconds and print the
shape of the resulting array.

In [34]:
mask = (times<=0.1) & (times>=0.2)
np.shape(eeg[:,:,mask])

(70, 59, 0)

<span class="theorem-title">**Exercise 28**</span> Take the average GFP
from <a href="#exr-avggfp" class="quarto-xref">Exercise 22</a>, get the
values between 0.085 and 0.115 seconds after stimulus onset and average
them. This is the amplitude of the so called N1 response.

In [35]:
mask = (times>=0.085) & (times<=0.115)
gfp[:,mask].mean(axis=0)

array([6.66245653e-06, 6.64888350e-06, 6.47134258e-06, 6.23569235e-06,
       6.12287725e-06])

<span class="theorem-title">**Exercise 29**</span> What is the time
point where the average GFP is the largest?

In [36]:
times[gfp.mean(axis=0).argmax()]

np.float64(0.2863731388603559)